secret_token: "b2d18fe98e6ae66a7a722aad1d8fe64055031ed9271c0d729f4fc4aabfa6f6f2c4316874b5705e743c4e338971c5a43de8dbdd0339492aee25e4b03e44a8fdd5"

development:
  mailer_host: "localhost:3000"
  mailer_from: "root@localhost"
  mailer_notify: "root@localhost"
  sepa_name: "Netz39 e.V." #Name of the initiating party and creditor, in German: "Auftraggeber", String, max. 70 char
  sepa_iban: 'DE87200500001234567890' #International Bank Account Number of the creditor. String, max. 34 chars
  sepa_creditor_identifier: 'DE98ZZZ09999999999' #Creditor Identifier, in German: Gläubiger-Identifikationsnummer. String, max. 35 chars

test:
  mailer_host: "localhost:3000"
  mailer_from: "root@localhost"
  mailer_notify: "root@localhost"
  sepa_name: "Netz39 e.V." #Name of the initiating party and creditor, in German: "Auftraggeber", String, max. 70 char
  sepa_iban: 'DE87200500001234567890' #International Bank Account Number of the creditor. String, max. 34 chars
  sepa_creditor_identifier: 'DE98ZZZ09999999999' #Creditor Identifier, in German: Gläubiger-Identifikationsnummer. String, max. 35 chars

production:
  mailer_host: "example.com"
  mailer_from: "root@example.com"
  mailer_notify: "root@localhost"
  mailer_protocol: "https"
  sepa_name: "Netz39 e.V." #Name of the initiating party and creditor, in German: "Auftraggeber", String, max. 70 char
  sepa_iban: 'DE87200500001234567890' #International Bank Account Number of the creditor. String, max. 34 chars
  sepa_creditor_identifier: 'DE98ZZZ09999999999' #Creditor Identifier, in German: Gläubiger-Identifikationsnummer. String, max. 35 chars
